/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketRouteImport } from './routes/market'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NovelsIndexRouteImport } from './routes/novels/index'
import { Route as NovelsNewRouteImport } from './routes/novels/new'
import { Route as NovelsIdRouteImport } from './routes/novels/$id'
import { Route as NovelsIdWorldRouteImport } from './routes/novels/$id.world'

const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelsIndexRoute = NovelsIndexRouteImport.update({
  id: '/novels/',
  path: '/novels/',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelsNewRoute = NovelsNewRouteImport.update({
  id: '/novels/new',
  path: '/novels/new',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelsIdRoute = NovelsIdRouteImport.update({
  id: '/novels/$id',
  path: '/novels/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelsIdWorldRoute = NovelsIdWorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => NovelsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/market': typeof MarketRoute
  '/novels/$id': typeof NovelsIdRouteWithChildren
  '/novels/new': typeof NovelsNewRoute
  '/novels/': typeof NovelsIndexRoute
  '/novels/$id/world': typeof NovelsIdWorldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/market': typeof MarketRoute
  '/novels/$id': typeof NovelsIdRouteWithChildren
  '/novels/new': typeof NovelsNewRoute
  '/novels': typeof NovelsIndexRoute
  '/novels/$id/world': typeof NovelsIdWorldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/market': typeof MarketRoute
  '/novels/$id': typeof NovelsIdRouteWithChildren
  '/novels/new': typeof NovelsNewRoute
  '/novels/': typeof NovelsIndexRoute
  '/novels/$id/world': typeof NovelsIdWorldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/market'
    | '/novels/$id'
    | '/novels/new'
    | '/novels/'
    | '/novels/$id/world'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/market'
    | '/novels/$id'
    | '/novels/new'
    | '/novels'
    | '/novels/$id/world'
  id:
    | '__root__'
    | '/'
    | '/market'
    | '/novels/$id'
    | '/novels/new'
    | '/novels/'
    | '/novels/$id/world'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarketRoute: typeof MarketRoute
  NovelsIdRoute: typeof NovelsIdRouteWithChildren
  NovelsNewRoute: typeof NovelsNewRoute
  NovelsIndexRoute: typeof NovelsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels/': {
      id: '/novels/'
      path: '/novels'
      fullPath: '/novels/'
      preLoaderRoute: typeof NovelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels/new': {
      id: '/novels/new'
      path: '/novels/new'
      fullPath: '/novels/new'
      preLoaderRoute: typeof NovelsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels/$id': {
      id: '/novels/$id'
      path: '/novels/$id'
      fullPath: '/novels/$id'
      preLoaderRoute: typeof NovelsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels/$id/world': {
      id: '/novels/$id/world'
      path: '/world'
      fullPath: '/novels/$id/world'
      preLoaderRoute: typeof NovelsIdWorldRouteImport
      parentRoute: typeof NovelsIdRoute
    }
  }
}

interface NovelsIdRouteChildren {
  NovelsIdWorldRoute: typeof NovelsIdWorldRoute
}

const NovelsIdRouteChildren: NovelsIdRouteChildren = {
  NovelsIdWorldRoute: NovelsIdWorldRoute,
}

const NovelsIdRouteWithChildren = NovelsIdRoute._addFileChildren(
  NovelsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarketRoute: MarketRoute,
  NovelsIdRoute: NovelsIdRouteWithChildren,
  NovelsNewRoute: NovelsNewRoute,
  NovelsIndexRoute: NovelsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
